### GetAll
http://localhost:5000/users 

### Get user by Id
http://localhost:5000/users/69338fddd7564a9cac3c5954

### Create user
POST http://localhost:5000/users
content-type: application/json

{
  "username": "Archbee",
  "displayName": "Deborah",
  "profileUrl": "https://github.com/Archbee"
}

### Put user by Id/username
PUT http://localhost:5000/users/Archbee HTTP/1.1 
content-type: application/json

{
  "username": "Beeangel",
  "displayName": "Okon",
  "profileUrl": "https://github.com/Archbee"
}

### Delete task by id
DELETE http://localhost:5000/users/69338fddd7564a9cac3c5954 HTTP/1.1 

### GetAll
http://localhost:5000/tasks 

### Get task by Id
http://localhost:5000/tasks/692671fe3f354dc56933b378

### Create task
POST http://localhost:5000/tasks
content-type: application/json

{
  "what": "18 mile run",
  "amount": "1",
  "reps": "1",
  "where": "track",
  "day": "Wednesday",
  "time": "7 pm"
}

### Put Task by Id
PUT http://localhost:5000/tasks/692a6f7dcc6ec3677e8808ed HTTP/1.1 
content-type: application/json

{
  "what": "2 mile run",
  "amount": "1",
  "reps": "1",
  "where": "track",
  "day": "Thursday",
  "time": "9 pm"
}

### Delete task by id
DELETE http://localhost:5000/tasks/692a49c08b79cdb82f436921 HTTP/1.1 

//Goals CRUD Request
### GetAll
http://localhost:5000/goals 

### Get goal by Id
http://localhost:5000/goals/692ad524b5cf10794ef69fe0

### Create goal
POST http://localhost:5000/goals
content-type: application/json

{
  "what": "7 one race",
  "time": "34 minutes"
}

### Put goal by Id
PUT http://localhost:5000/goals/692ad524b5cf10794ef69fe0 HTTP/1.1 
content-type: application/json

{
  "what": "bleacher miles",
  "time": "12 minutes"
}

### Delete goal by id
DELETE http://localhost:5000/goals/692ad524b5cf10794ef69fe0 HTTP/1.1

//Events CRUD Request
### GetAll
http://localhost:5000/events 

### Get event by Id
http://localhost:5000/events/692ad524b5cf10794ef69fe0


